// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOJ4MxNASpaqEqdk4j2gQnTK5S3Zviwc',
    appId: '1:583656710682:web:a81e6ff405de628dcd67a3',
    messagingSenderId: '583656710682',
    projectId: 'chat-app-2b0af',
    authDomain: 'chat-app-2b0af.firebaseapp.com',
    storageBucket: 'chat-app-2b0af.firebasestorage.app',
    measurementId: 'G-Z02WEL7XWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuA6RKp7ZLqD3SkoeAgcP-0J5jXgn7JQw',
    appId: '1:583656710682:android:81a1ca7193686983cd67a3',
    messagingSenderId: '583656710682',
    projectId: 'chat-app-2b0af',
    storageBucket: 'chat-app-2b0af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDZI9Xi2EJWXslD7DkP4kbEk1VFPJlZ0',
    appId: '1:583656710682:ios:140cfc4d6f7f1aa0cd67a3',
    messagingSenderId: '583656710682',
    projectId: 'chat-app-2b0af',
    storageBucket: 'chat-app-2b0af.firebasestorage.app',
    iosBundleId: 'com.example.cahtApp',
  );
}
